name: Flutter CI

on: [ push, pull_request ]

jobs:
  # This job will run all the necessary checks.
  lint-test-build:
    name: Lint, Test, and Build
    runs-on: windows-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4


      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          cache: true
          channel: stable
          flutter-version-file: pubspec.yaml


      - name: Install dependencies
        run: flutter pub get

      - name: Analyze project source
        run: flutter analyze


      - name: Run tests
        run: flutter test

      - name: Build Windows release
        run: flutter build windows --release